### ISSUE TITLE
Valgrind helgrind/drd thread data race warnings

### ISSUE THREAD

**Issue by zevv** [guzba/mummy#10]
Hey Guzba,

Over the last few weeks I have been spending time on some experiments to see if and how robust multithreading can be done in "modern" Nim; This started from some discussions I recently had with Araq about the interactions between the non-atomic ARC reference counters and threads, and the conclusion was that this is currently not trivial to do without violating the underlying memory model.

(See https://forum.nim-lang.org/t/9617 for some background info)

Only today I found your mummy project, which is pretty interesting as it has some nice overlaps with what I am trying to accomplish. I was curious to see if you have run into any of the issues I ran into, and how you coped with these. My first test was to run mummy under valgrind's "helgrind" and "drd" analyzers to see if it finds any suspicious behavior, and indeed it seems to do so, I attached the output below.

I must admit I have not yet looked at your implementation, I merely ran the test; helgrind and drd are known to occasionally emit false positives, so my report might not be valid.

Reproduction path:

- Checkout mummy 0.1.1
- write a simple main.nim with the example webserver from the README
- compile with `nim c --gc:orc -d:release --debugger:native main.nim`
- run with `valgrind --tool=helgrind ./main`

Let me know if you have any questions, I'd be happy to discuss the details. 

[mummy-drd.txt](https://github.com/guzba/mummy/files/10155680/mummy-drd.txt)
[mummy-helgrind.txt](https://github.com/guzba/mummy/files/10155682/mummy-helgrind.txt)

**Comment by guzba** [comment]
Thanks for taking a look at Mummy.

I think Helgrind isn't going to work for this project. From their docs:

>Do not roll your own threading primitives (mutexes, etc) from combinations of the Linux futex syscall, atomic counters, etc. These throw Helgrind's internal what's-going-on models way off course and will give bogus results.

Mummy uses atomics for mutexes etc by default on Linux so that'll be a problem for Helgrind. There is -d:mummyUseLockAndCond but it is not the default.

It's not stated as clearly for DRD but it appears DRD needs macros / annotations to understand atomics as well? Referencing:

> The purpose of these two macros is to tell DRD about the order of inter-thread memory accesses implemented via atomic memory operations.

Maybe you're more familiar with these rules? I also recall seeing that -d:useMalloc can be required for Valgrind with Nim. Not sure if that would clear up all the Nim allocator related entries or not.

**Comment by guzba** [comment]
One thing I've been careful to do with Mummy is side-step the ref counting issue. I never have multiple threads with a reference to a ref object. In fact, there is not a single public ref object for Mummy at all (internally there are a couple, and I use `move` to make sure there's no references in more places than I carefully control).

I have chosen to make the Request object something I manually manage the memory for (it can have a simply defined lifecycle so this is pretty easy). There are further benefits but I've not put out an example of what I did that for yet. Everything else is what Nim treats as value types (basic stuff like ints, plus strings).

**Comment by zevv** [comment]
Right, the refs are a pita to handle when threading, so the best approach is indeed not to have more then one thread own a ref at any time. You can synchronize your own data all you want, but it's virtually impossible to keep the RCs themselves safe because it's Nim who decides how to touch them and when.

I still do see a number of `eqdestroy__` and `nimIncRef` instances pop up, even with `-d:mummyUseLockAndCond`, so you might want to keep an eye out for those.

Good Nimming!
