### ISSUE TITLE
Allow raw socket handlers

### ISSUE THREAD

**Issue by turbo** [guzba/mummy#100]
I'm migrating my last few apps to Mummy and I am currently working on one that was previously based on nginx/openresty that uses raw sockets in addition to http.

In the existing app, a Lua program listens for sockets requests (what it does isn't important):

```nginx
http { 
  # normal web stuff
}
stream {
  server {
    listen 1234;
    content_by_lua_file "lualib/senna/serve_tcp.lua";
  }
}
```

A socket handler would work much the same way: instead of a Request, it receives the raw duplex SocketHandle (or an abstraction), reads and writes its bytes, then returns when done. For this to work well, the handler must be the only code consuming or writing data to the socket after it has been accepted.

While this is easy enough to implement in straight Nim, I'd like to re-use the thread dispatching that mummy already does well.

**Comment by guzba** [comment]
Sorry, I have no need of this and do not want to implement or support it. I suggest forking Mummy and adding whatever support you need there.
