### ISSUE TITLE
Unable to use a 'ref' object in a route handler?

### ISSUE THREAD

**Issue by matkuki** [guzba/mummy#115]
Hi,

This code uses a global `ref` object in the `index_handler`:
```nim
import
    mummy,
    mummy/routers

type
    TestRef = ref object
        name: string

var
    new_ref = new(TestRef)
new_ref.name = "<div>Hello World</div>"

proc index_handler(request: Request) =
    var headers: HttpHeaders
    headers["Content-Type"] = "text/html"
    let content: string = new_ref.name # <- HERE IS THE PROBLEM
    request.respond(200, headers, $content)

proc main() =
    var router: Router
    router.get("/", index_handler)
    
    let
        server = newServer(router)
        ip_address = "0.0.0.0"
    echo "Serving on http://localhost:8080"
    server.serve(Port(8080), address=ip_address)

if is_main_module:
    main()
```
which in turn throws this error:
```
mummy_test.nim(21, 11) Error: type mismatch                                   
Expression: get(router, "/", index_handler)                                                    
  [1] router: Router                                                                           
  [2] "/": string                                                                              
  [3] index_handler: proc (request: Request)                                                   
                                                                                               
Expected one of (first mismatch at [position]):                                                
[3] proc get(router: var Router; route: string | static string;                                
         handler: RequestHandler)
```
This is a contrived example, in my original code I use the [tim](https://github.com/openpeeps/tim) library which uses a `ref` object to generate `HTML` templates, but it's the same problem.

Is there a solution for this?

**Comment by guzba** [comment]
Nim's `ref object` is not thread safe so it must be used with extreme care if threads are being used (almost certainly going to be broken).

I am sorry that I cannot explain super deeply here, it is a deep topic, but you'll either need to ensure all `ref object`s are only ever instantiated and used in one thread (a handler call tree). This is because the reference count is not thread-safe or atomic. Some searching about Nim `ref object` and threads and --mm:arc/orc will find some discussion on the Nim forums.

**Comment by guzba** [comment]
(I should also note that the error in your post does not appear to be related to the area of the code you're highlighting.)

**Comment by matkuki** [comment]
Thanks.

> I should also note that the error in your post does not appear to be related to the area of the code you're highlighting.

Correct, the problem is the indicated line, the error is for the `router.get("/", index_handler)` call.
I just wanted to highlight that I had no idea what was wrong for quite some time, as the error message does not indicate where the problem is. In the original code I use the `tim` library, which I didn't know returned a `ref` object for generating `HTML` code, so it was weird as I just changed one line and it stopped working:
```nim
proc index_handler(request: Request) =
    var headers: HttpHeaders
    headers["Content-Type"] = "text/html"
    let content: string = timl.render("index")
    request.respond(200, headers, $content)
```
So I guess `tim` in not suited to for use with `mummy`.
