### ISSUE TITLE
[Question] Chaining Routers

### ISSUE THREAD

**Issue by vabresto** [guzba/mummy#47]
Hey, great library! Was trying it out over the weekend and I can't seem to find a way to chain routers together. Pardon me if I've missed something obvious, since it seems like it's really close to working. It looks like `addRoute` and `convertToHandler` got me 90% of the way there, but doing something like

```nim
## index.nim
import mummy
import mummy/routers

func renderPage(): string =
  "index page"

proc fooHandler(request: Request) =
  var headers: HttpHeaders
  headers["Content-Type"] = "text/html"
  request.respond(200, headers, renderPage())

var fooRouter*: Router
fooRouter.get("/", fooHandler)


## main.nim
import mummy
import mummy/routers

import index

proc indexHandler*(request: Request) =
  var headers: HttpHeaders
  headers["Content-Type"] = "text/plain"
  request.respond(200, headers, "Hello, World!")

var router: Router
router.get("/", indexHandler)
router.addRoute("GET", "/foo", fooRouter.toHandler()) # <-- 

let server = newServer(router)
server.serve(9090.Port, "0.0.0.0")

```

doesn't quite work - it just 404s on the `/foo` route (though `/` works fine and prints hello world).

**Comment by guzba** [comment]
Hi, you can have a router get called by another router, but each layer of the path matching would need to work. Specifically having a router get called from a route of another router is not really how I intended things to get used.

In the case of the example above, I would not try to compose multiple routers and instead just have multiple routes set up on on router. This is the intended usage.

```nim
## index.nim
import mummy
import mummy/routers

func renderPage(): string =
  "index page"

proc fooHandler(request: Request) =
  var headers: HttpHeaders
  headers["Content-Type"] = "text/html"
  request.respond(200, headers, renderPage())

proc indexHandler*(request: Request) =
  var headers: HttpHeaders
  headers["Content-Type"] = "text/plain"
  request.respond(200, headers, "Hello, World!")

var router: Router
router.get("/", indexHandler)
router.get("/foo", fooHandler)

let server = newServer(router)
server.serve(9090.Port, "0.0.0.0")
```

**Comment by vabresto** [comment]
Thanks for the reply! The reasoning for asking about this is that it should be easy to move routes around (change one location instead of every single route), and it also makes it cleaner (imo) to bubble up routers instead of individual handlers.

Concretely, you might have 
```nim
router.get("/auth/register", ...)
router.get("/auth/register", ...)
router.get("/auth/register", ...)
```

**Comment by vabresto** [comment]
I see, thanks. I don't necessarily love layering at the router level either, but I do feel like having the handlers and their routes together (locality) is useful. I'll think on this a bit more. Thanks!
