### ISSUE TITLE
Bad performance on windows os due to failed "Maximum number of descriptors is exhausted!"

### ISSUE THREAD

**Issue by me7** [guzba/mummy#95]
I tried wrk_mummy.nim per https://github.com/guzba/mummy#mummy-1 example but it's fail "Maximum number of descriptors is exhausted!" and die everytime.
  What I assume is because FD_SETSIZE in std/selectors is set to 1024 and exhaused so it's get this error when concurrent connection is set to 100
![image](https://github.com/guzba/mummy/assets/10399270/980460fd-86a0-49fa-99d4-3ba356f814c2)

when reduce concurrent connection to 50 server is working ok with about 4.4k requests/second
![image](https://github.com/guzba/mummy/assets/10399270/dbeff877-019f-4219-969e-233d0c6b957f)

How to resolve this issue? Otherwise I think it's cannot use on windows system.

---
note 1.  I use [plow](https://github.com/six-ddc/plow) to benchmark due to wrk is not available on windows.
note 2.  for comparison, simple node http server can easily handle 100 concurrent connection with 13k requests/second but right now mummy will die if concurrent connection is more than 50.
![image](https://github.com/guzba/mummy/assets/10399270/ec3d5b87-ff8e-4e1d-a752-28bc511dad5f)

**Comment by guzba** [comment]
Windows support is only present to enable development for those that prefer to work on Windows. Benchmarking or running Mummy in production is always expected to be on Linux. Benchmarks on Windows will be of no value to a Linux production environment.

**Comment by me7** [comment]
Thank you for clarification. So this mean mummy is not design to run in production for windows os?

Not offending, just curios because now I use Jester on windows and it's not have this problem of "file descripter exhausted"
I want to change my app to use mummy instead of jester due to it's native support for websocket, but if this is by design to run better on linux I will stay with jester.

**Comment by guzba** [comment]
No prob to ask. That is correct, Mummy is not not tested nor intended to be run in production on Windows. I'm not aware of any HTTP servers other than .NET stuff that is actually intended to run on Windows in production as that is quite rare.
